export const Images = {
    onBoard: require('../images/onBoardLight.png'),
    carMove: require('../images/onBoardCardMove.png'),
    carIcon: require('../images/carIcon.png'),
    backArrow: require('../images/Back-arrow.png'),
    backArrowDark: require('../images/Back-arrow-dark.png'),
    logo: require('../images/logo.png'),
    userAvatar: require('../images/man.png'),
    addImage: require('../images/plus.png'),
    notification: require('../images/notification.png'),
    bookcard: require('../images/book-card.png'),
    Usedcard: require('../images/Usedcard.png'),
    ParkCar: require('../images/parkcar.png'),
    payments: require('../images/wallet.png'),
    payment: require('../images/payment-method.png'),
    bookingHistory: require('../images/scroll.png'),
    paymentHistory: require('../images/transaction-history.png'),
    profilenotification: require('../images/profilenotification.png'),
    settings: require('../images/setting.png'),
    logout: require('../images/logout.png'),
    settleup: require('../images/deal.png'),
    pay: require('../images/payment-methodNew.png'),
    success: require('../images/checked.png'),
    loader: require('../images/loader.gif'),
    booking: require('../images/booking.png'),
    noBookings: require('../images/nodata.gif'),
};
